[package]
name = "edict"
version = "0.4.0-rc.2"
edition = "2021"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/edict"
homepage = "https://github.com/zakarumych/edict"
repository = "https://github.com/zakarumych/edict"
readme = "README.md"
description = "Experimental entity-component-system library"
keywords = ["ecs", "entity"]
categories = ["no-std", "game-development", "data-structures"]

[features]
std = []
default = ["std"]

[dependencies]
edict-proc = { version = "=0.3.0", path = "proc" }
hashbrown = { version = "0.13", features = ["ahash"], default-features = false }
smallvec = { version ="1.8", features = ["union"], default-features = false }
tiny-fn = "0.1.5"
atomicell = "0.1.8"
flume = { version = "0.10" }
rayon = { version = "1.5", optional = true }

[workspace]
members = ["proc-lib", "proc"]
